// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package opensearch

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Number of OpenSearch nodes in the cluster.
	// +kubebuilder:default:=3
	Replicas int `json:"replicas"`
	// Explicit CPU and memory configuration for each OpenSearch node. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted. OpenSearch requires minimum 2Gi memory.
	// +kubebuilder:default:="c1.medium"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
	// Persistent Volume Claim size available for application data.
	// +kubebuilder:default:="10Gi"
	Size resource.Quantity `json:"size"`
	// StorageClass used to store the data.
	// +kubebuilder:default:=""
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="storageClass is immutable"
	StorageClass string `json:"storageClass"`
	// Enable external access from outside the cluster.
	// +kubebuilder:default:=false
	External bool `json:"external"`
	// How strictly to enforce pod distribution across nodes and zones.
	// +kubebuilder:default:="soft"
	TopologySpreadPolicy TopologySpreadPolicy `json:"topologySpreadPolicy"`
	// OpenSearch major version to deploy.
	// +kubebuilder:default:="v2"
	Version Version `json:"version"`
	// HTTP-layer TLS configuration. Selects who issues the HTTP server certificate; TLS itself is always served.
	// +kubebuilder:default:={}
	Tls TLS `json:"tls"`
	// Container images used by the operator.
	// +kubebuilder:default:={}
	Images Images `json:"images"`
	// Node roles configuration.
	// +kubebuilder:default:={}
	NodeRoles NodeRoles `json:"nodeRoles"`
	// Custom OpenSearch users configuration map.
	// +kubebuilder:default:={}
	Users map[string]User `json:"users,omitempty"`
	// OpenSearch Dashboards configuration.
	// +kubebuilder:default:={}
	Dashboards Dashboards `json:"dashboards"`
}

type Dashboards struct {
	// Enable OpenSearch Dashboards deployment. The application name is then limited to 41 characters, and to 32 when external access is also on, because the Dashboards Service the operator creates would otherwise exceed the 63-character DNS label limit, and the operator stops upgrading and restarting the release for as long as that Service is refused.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Number of Dashboards replicas.
	// +kubebuilder:default:=1
	Replicas int `json:"replicas"`
	// Explicit CPU and memory configuration for Dashboards.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset for Dashboards.
	// +kubebuilder:default:="c1.small"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
}

type Images struct {
	// OpenSearch image.
	// +kubebuilder:default:=""
	Opensearch string `json:"opensearch"`
}

type NodeRoles struct {
	// Enable data role.
	// +kubebuilder:default:=true
	Data bool `json:"data"`
	// Enable ingest role.
	// +kubebuilder:default:=true
	Ingest bool `json:"ingest"`
	// Enable cluster_manager role.
	// +kubebuilder:default:=true
	Master bool `json:"master"`
	// Enable machine learning role.
	// +kubebuilder:default:=false
	Ml bool `json:"ml"`
}

type Resources struct {
	// CPU available to each node.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available to each node.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type TLS struct {
	// Who issues the HTTP server certificate: `operator` uses the CA the opster operator manages itself, `cert-manager` gives the release its own CA, covers the external hostname and publishes a trust anchor the tenant can verify against. Unset follows external: `cert-manager` when it is true, `operator` when it is false. Named for the issuer because TLS is served under both, unlike the similarly-spelled `tls.enabled` in some other charts, which does switch TLS on and off.
	Issuer TLSIssuer `json:"issuer,omitempty"`
}

type User struct {
	// Password for the user (auto-generated if omitted).
	Password string `json:"password,omitempty"`
	// List of OpenSearch roles.
	Roles []string `json:"roles,omitempty"`
}

// +kubebuilder:validation:Enum="t1.nano";"t1.micro";"t1.small";"t1.medium";"t1.large";"t1.xlarge";"t1.2xlarge";"t1.4xlarge";"c1.nano";"c1.micro";"c1.small";"c1.medium";"c1.large";"c1.xlarge";"c1.2xlarge";"c1.4xlarge";"s1.nano";"s1.micro";"s1.small";"s1.medium";"s1.large";"s1.xlarge";"s1.2xlarge";"s1.4xlarge";"u1.nano";"u1.micro";"u1.small";"u1.medium";"u1.large";"u1.xlarge";"u1.2xlarge";"u1.4xlarge";"m1.nano";"m1.micro";"m1.small";"m1.medium";"m1.large";"m1.xlarge";"m1.2xlarge";"m1.4xlarge";"nano";"micro";"small";"medium";"large";"xlarge";"2xlarge"
type ResourcesPreset string

// +kubebuilder:validation:Enum="operator";"cert-manager"
type TLSIssuer string

// +kubebuilder:validation:Enum="soft";"hard"
type TopologySpreadPolicy string

// +kubebuilder:validation:Enum="v3";"v2";"v1"
type Version string
