apiVersion: v2
name: valkey
description: Managed Valkey service
icon: /logos/valkey.svg
type: application
version: 0.0.0 # Placeholder, the actual version will be automatically set during the build process
appVersion: "8.1.8"
