---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.vm-adoption-controller
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.kubevirt
    - cozystack.forklift
    components:
    - name: vm-adoption-controller
      path: system/vm-adoption-controller
      install:
        namespace: cozy-forklift
        releaseName: vm-adoption-controller
