#!/bin/bash
# adopt-vm.sh - Adopt an imported VM into Cozystack Helm management
#
# Usage: ./adopt-vm.sh <vm-name> <namespace> [instance-type] [profile]
#
# Example:
#   ./adopt-vm.sh web-server default u1.medium ubuntu

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Arguments
VM_NAME="${1:?$(echo -e "${RED}Error: VM name required${NC}\nUsage: $0 <vm-name> <namespace> [instance-type] [profile]")}"
NAMESPACE="${2:?$(echo -e "${RED}Error: Namespace required${NC}\nUsage: $0 <vm-name> <namespace> [instance-type] [profile]")}"
INSTANCE_TYPE="${3:-u1.medium}"
PROFILE="${4:-ubuntu}"

OUTPUT_FILE="/tmp/adopt-${VM_NAME}-values.yaml"

echo -e "${GREEN}=== Cozystack VM Adoption Tool ===${NC}"
echo "VM Name: $VM_NAME"
echo "Namespace: $NAMESPACE"
echo "Instance Type: $INSTANCE_TYPE"
echo "Profile: $PROFILE"
echo ""

# Check if VM exists
echo -e "${YELLOW}[1/5]${NC} Checking if VM exists..."
if ! kubectl get vm "$VM_NAME" -n "$NAMESPACE" &>/dev/null; then
    echo -e "${RED}Error: VM '$VM_NAME' not found in namespace '$NAMESPACE'${NC}"
    exit 1
fi
echo -e "${GREEN}✓${NC} VM found"

# Extract current configuration
echo -e "${YELLOW}[2/5]${NC} Extracting current VM configuration..."
RUNNING=$(kubectl get vm "$VM_NAME" -n "$NAMESPACE" -o jsonpath='{.spec.running}' 2>/dev/null || echo "false")
echo "  Running state: $RUNNING"

# Check if VM has Forklift labels
IS_IMPORTED=$(kubectl get vm "$VM_NAME" -n "$NAMESPACE" -o jsonpath='{.metadata.labels.forklift\.konveyor\.io/plan}' 2>/dev/null || echo "")
if [ -n "$IS_IMPORTED" ]; then
    echo -e "  ${GREEN}✓${NC} VM was imported via Forklift (plan: $IS_IMPORTED)"
else
    echo -e "  ${YELLOW}⚠${NC}  VM was not imported via Forklift (manual creation?)"
fi

# Find attached DataVolumes
echo -e "${YELLOW}[3/5]${NC} Discovering attached disks..."
DISK_NAMES=$(kubectl get vm "$VM_NAME" -n "$NAMESPACE" -o json 2>/dev/null | \
  jq -r '.spec.template.spec.volumes[]? | select(.dataVolume) | .dataVolume.name' || echo "")

if [ -z "$DISK_NAMES" ]; then
    echo -e "  ${YELLOW}⚠${NC}  No DataVolumes found attached to VM"
    DISKS_YAML="  # No disks found - add manually if needed"
else
    DISKS_YAML=""
    DISK_COUNT=0
    while IFS= read -r disk; do
        if [ -n "$disk" ]; then
            ((DISK_COUNT++))
            echo "  - $disk"
            # Extract disk name without vm- prefix if present
            DISK_REF=$(echo "$disk" | sed "s/^vm-disk-//")
            DISKS_YAML="${DISKS_YAML}  - name: ${DISK_REF}
    bus: virtio
"
        fi
    done <<< "$DISK_NAMES"
    echo -e "  ${GREEN}✓${NC} Found $DISK_COUNT disk(s)"
fi

# Check for SSH keys
echo -e "${YELLOW}[4/5]${NC} Checking for SSH keys..."
SSH_SECRET="${VM_NAME}-ssh-keys"
if kubectl get secret "$SSH_SECRET" -n "$NAMESPACE" &>/dev/null; then
    echo -e "  ${GREEN}✓${NC} Found existing SSH keys secret: $SSH_SECRET"
    SSH_KEYS_YAML="  # SSH keys found in secret: $SSH_SECRET
  # Add additional keys here if needed"
else
    echo -e "  ${YELLOW}⚠${NC}  No SSH keys secret found"
    SSH_KEYS_YAML="  # No SSH keys found - add your public keys here"
fi

# Check for networks
echo "Checking network configuration..."
NETWORKS=$(kubectl get vm "$VM_NAME" -n "$NAMESPACE" -o json 2>/dev/null | \
  jq -r '.spec.template.spec.networks[]? | select(.multus) | .multus.networkName' || echo "")

if [ -n "$NETWORKS" ]; then
    echo -e "  ${GREEN}✓${NC} Found Multus networks:"
    SUBNETS_YAML="subnets:"
    while IFS= read -r net; do
        if [ -n "$net" ]; then
            echo "  - $net"
            # Extract subnet name (remove namespace prefix if present)
            SUBNET_NAME=$(echo "$net" | sed 's/^.*\///')
            SUBNETS_YAML="${SUBNETS_YAML}
  - name: ${SUBNET_NAME}"
        fi
    done <<< "$NETWORKS"
else
    echo "  No Multus networks found (using pod network)"
    SUBNETS_YAML="# No additional subnets (using pod network only)"
fi

# Generate values file
echo -e "${YELLOW}[5/5]${NC} Generating Helm values file..."
cat > "$OUTPUT_FILE" <<EOF
# Cozystack vm-instance values for adopting: $VM_NAME
# Generated by adopt-vm.sh on $(date)
#
# Review and customize this file, then apply with:
#   helm upgrade --install "$VM_NAME" cozystack/vm-instance \\
#     --namespace "$NAMESPACE" \\
#     --values $OUTPUT_FILE

# === Basic Configuration ===
running: ${RUNNING}

# === Instance Configuration ===
instanceType: ${INSTANCE_TYPE}
instanceProfile: ${PROFILE}

# Alternatively, specify custom resources:
# resources:
#   cpu: 4
#   memory: 8Gi
#   sockets: 1

# === Disks ===
disks:
${DISKS_YAML}

# === Network Configuration ===
${SUBNETS_YAML}

# External access (LoadBalancer service)
external: false
# externalPorts:
#   - 22
#   - 80
#   - 443

# === Access Credentials ===
sshKeys:
${SSH_KEYS_YAML}

# === Cloud-Init ===
# IMPORTANT: Avoid re-running cloud-init on adopted VMs
# as it may reset networking or other configuration.
# Only enable if you need to reconfigure the VM.
cloudInit: ""

# Seed value - change only if you need cloud-init to re-run
cloudInitSeed: "imported-vm"

# === GPU Configuration ===
# gpus:
#   - name: gpu1
#     deviceName: "nvidia.com/GP102GL_Tesla_P40"

# === Advanced Options ===
# Enable if VM was migrated from Windows
# This sets proper node affinity for Windows VMs
# windowsVM: false
EOF

echo -e "${GREEN}✓${NC} Values file generated: $OUTPUT_FILE"
echo ""

# Display summary
echo -e "${GREEN}=== Adoption Summary ===${NC}"
echo "VM: $VM_NAME (namespace: $NAMESPACE)"
echo "Current state: $([ "$RUNNING" = "true" ] && echo "Running" || echo "Stopped")"
echo "Disks: $(echo "$DISKS_YAML" | grep -c "name:" || echo "0")"
echo "Values file: $OUTPUT_FILE"
echo ""

# Instructions
echo -e "${GREEN}=== Next Steps ===${NC}"
echo "1. Review and edit the values file:"
echo -e "   ${YELLOW}vim $OUTPUT_FILE${NC}"
echo ""
echo "2. Apply the adoption (this will create a Helm release):"
echo -e "   ${YELLOW}helm upgrade --install \"$VM_NAME\" cozystack/vm-instance \\${NC}"
echo -e "   ${YELLOW}     --namespace \"$NAMESPACE\" \\${NC}"
echo -e "   ${YELLOW}     --values $OUTPUT_FILE${NC}"
echo ""
echo "3. Verify the adoption:"
echo -e "   ${YELLOW}helm list -n \"$NAMESPACE\"${NC}"
echo -e "   ${YELLOW}kubectl get vm \"$VM_NAME\" -n \"$NAMESPACE\" -o yaml | grep -A 5 'app.kubernetes.io/managed-by'${NC}"
echo ""
echo -e "${YELLOW}⚠  Important:${NC} The VM and its disks will NOT be modified during adoption."
echo "   The Helm release will manage future changes via declarative values."
echo ""
